image: alpine/latest
packages:
  - go
  - rsync
  - ssh
sources:
  - https://git.sr.ht/~sauerbraten/chef
environment:
  DEPLOY: chef.sauerworld.org
secrets:
  - 98c1b481-b37f-452f-872a-8f8fa1833249
tasks:
  - setup: |
      ssh $DEPLOY 'if [ ! -f .z ] ; then echo "yes"; fi'
  - build: |
      cd chef/cmd/chef
      go build
  - deploy: |
      cd chef
      rsync chef.sqlite.schema $DEPLOY:~/chef/
      ssh $DEPLOY 'if [ ! -f ~/.chef.sqlite ] ; then sqlite3 ~/.chef.sqlite < chef.sqlite.schema ; fi'
      cd cmd/chef
      rsync css templates config.json chef $DEPLOY:~/chef/
      ssh $DEPLOY 'killall chef && nohup ./chef &>> logs/chef.txt &'
