image: alpine/edge
packages:
  - go
  - rsync
sources:
  - https://git.sr.ht/~sauerbraten/chef
environment:
  DEPLOY: chef.sauerworld.org
  GOPATH: $HOME
secrets:
  - 98c1b481-b37f-452f-872a-8f8fa1833249
tasks:
  - build: |
      mkdir -p src/github.com/sauerbraten
      mv chef src/github.com/sauerbraten/
      cd src/github.com/sauerbraten/chef/cmd/chef
      go get
      go build
  - version: |
      cd src/github.com/sauerbraten/chef/cmd/chef
      sed -i "s/<filled in by CI service>/$(git rev-parse --short HEAD)/" config.json
  - deploy: |
      cd src/github.com/sauerbraten/chef
      rsync --rsh="ssh -o StrictHostKeyChecking=no" -rP chef.sqlite.schema ci@$DEPLOY:~/chef/
      ssh -o StrictHostKeyChecking=no ci@$DEPLOY 'cd chef; if [ ! -f chef.sqlite ] ; then sqlite3 chef.sqlite < chef.sqlite.schema ; fi'
      cd cmd/chef
      rsync --rsh="ssh -o StrictHostKeyChecking=no" -rP css templates config.json chef ci@$DEPLOY:~/chef/
      ssh -o StrictHostKeyChecking=no ci@$DEPLOY 'killall chef'
      ssh -o StrictHostKeyChecking=no ci@$DEPLOY 'cd chef; nohup ./chef &>> log.txt &'
