image: alpine/edge
packages:
  - go
  - rsync
sources:
  - https://github.com/sauerbraten/chef
environment:
  DEPLOY: chef.p1x.pw
  GOPATH: $HOME
secrets:
  - 41a695fb-4229-450d-9aa4-5499f6bcea81
tasks:
  - prepare_go_modules: |
      go env -w mod=vendor
  - version: |
      cd chef/cmd/chef
      sed -i "s/<filled in by CI service>/$(git rev-parse --short HEAD)/" main.go
  - build: |
      cd chef
      go build ./cmd/chef
  - deploy: |
      cd chef
      rsync --rsh="ssh -o StrictHostKeyChecking=no" -rPq chef.sqlite.schema ci@$DEPLOY:~/chef/
      ssh -o StrictHostKeyChecking=no ci@$DEPLOY 'cd chef; if [ ! -f chef.sqlite ] ; then sqlite3 chef.sqlite < chef.sqlite.schema ; fi'
      rsync --rsh="ssh -o StrictHostKeyChecking=no" -rPq css templates config.json chef ci@$DEPLOY:~/chef/
      ssh -o StrictHostKeyChecking=no ci@$DEPLOY 'killall chef || true'
      ssh -o StrictHostKeyChecking=no ci@$DEPLOY 'cd chef; nohup ./chef >> log.txt 2>&1 &'
